# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'arkitlearning' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for arkitlearning

  target 'arkitlearningTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
pod 'RNSensors', :path => '../node_modules/react-native-sensors'
